### ISSUE TITLE
Add support for Laravel 10.x ?

### ISSUE THREAD

**Issue by hoangnamitc** [ryangjchandler/standalone-blade#9]
Hello,

According to the contents of the composer file, this package **only supports** version 10.

By laravel 9 support from PHP 8.0

<img width="511" alt="Screenshot 2023-02-25 at 10 01 17" src="https://user-images.githubusercontent.com/7042462/221332820-4614a8cd-4586-4b41-aa5e-d9e4ff1ade72.png">

**Comment by ryangjchandler** [comment]
Laravel 10 requires PHP 8.1+. I have no interest in supporting Laravel 9, or PHP 8.0 since it's end of life.
